### ISSUE TITLE
Logo Design For Strees Detection Kit

### ISSUE THREAD

**Issue by zularizal** [baygeldin/StressDetectionKit#1]
Hi @baygeldin ,I am a graphic designer, I want to help others in graphic design.

After I review your project, your app is very good. But I think your icon is irrelevant to your application. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by baygeldin** [comment]
Thank for the offer, but this app is just for educational purposes (so to say). I have no intent to publish it, so the current icon will do just fine.
